# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Muhammed Yavuz Nuzumlalı'
email: manuyavuz@gmail.com
description: |
  Ph.D. Student @CmpeBOUN
  Core Team Member @CocoaPods
  iOS Tech Lead & Machine Learning Engineer @Netmera
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: manuyavuz
github_username:  manuyavuz
redirects: yes

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-scholar-extras
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock




#### SCHOLAR ####
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: _bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
